from __future__ import annotations

from importlib import import_module
from typing import Any

_MODEL_EXPORTS = {
    "WhatIfEpisodeManifest",
    "WhatIfEpisodeMaterialization",
    "WhatIfEventSearchResult",
    "WhatIfExperimentResult",
    "WhatIfCounterfactualEstimateResult",
    "WhatIfBusinessConsequenceEstimate",
    "WhatIfBusinessStateAssessment",
    "WhatIfBusinessStateChange",
    "WhatIfBusinessStateImpact",
    "WhatIfBusinessStateIndicator",
    "WhatIfBusinessStateSnapshot",
    "WhatIfBranchCandidate",
    "WhatIfBranchCandidateResult",
    "WhatIfCaseContext",
    "WhatIfCaseRecord",
    "WhatIfCaseSummary",
    "WhatIfBenchmarkBuildResult",
    "WhatIfBenchmarkEvalResult",
    "WhatIfBenchmarkJudgeResult",
    "WhatIfBenchmarkStudyResult",
    "WhatIfBenchmarkTrainResult",
    "WhatIfLLMReplayResult",
    "WhatIfBackendScore",
    "WhatIfCandidateIntervention",
    "WhatIfCandidateRanking",
    "WhatIfDecisionOption",
    "WhatIfDecisionScene",
    "WhatIfObjectivePack",
    "WhatIfOutcomeScore",
    "WhatIfOutcomeSignals",
    "WhatIfPackRunResult",
    "WhatIfPublicContext",
    "WhatIfPublicFinancialSnapshot",
    "WhatIfPublicNewsEvent",
    "WhatIfRankedExperimentResult",
    "WhatIfReplaySummary",
    "WhatIfResearchPack",
    "WhatIfResult",
    "WhatIfScenario",
    "WhatIfSituationCluster",
    "WhatIfSituationContext",
    "WhatIfSituationGraph",
    "WhatIfSituationLink",
    "WhatIfSituationThread",
    "WhatIfWorld",
}

__all__ = [
    "WhatIfEpisodeManifest",
    "WhatIfEpisodeMaterialization",
    "WhatIfEventSearchResult",
    "WhatIfExperimentResult",
    "WhatIfCounterfactualEstimateResult",
    "WhatIfBusinessConsequenceEstimate",
    "WhatIfBusinessStateAssessment",
    "WhatIfBusinessStateChange",
    "WhatIfBusinessStateImpact",
    "WhatIfBusinessStateIndicator",
    "WhatIfBusinessStateSnapshot",
    "WhatIfBranchCandidate",
    "WhatIfBranchCandidateResult",
    "WhatIfCaseContext",
    "WhatIfCaseRecord",
    "WhatIfCaseSummary",
    "WhatIfBenchmarkBuildResult",
    "WhatIfBenchmarkEvalResult",
    "WhatIfBenchmarkJudgeResult",
    "WhatIfBenchmarkStudyResult",
    "WhatIfBenchmarkTrainResult",
    "WhatIfLLMReplayResult",
    "WhatIfBackendScore",
    "WhatIfCandidateIntervention",
    "WhatIfCandidateRanking",
    "WhatIfDecisionOption",
    "WhatIfDecisionScene",
    "WhatIfObjectivePack",
    "WhatIfOutcomeScore",
    "WhatIfOutcomeSignals",
    "WhatIfPackRunResult",
    "WhatIfPublicContext",
    "WhatIfPublicFinancialSnapshot",
    "WhatIfPublicNewsEvent",
    "WhatIfRankedExperimentResult",
    "WhatIfReplaySummary",
    "WhatIfResearchPack",
    "WhatIfResult",
    "WhatIfScenario",
    "WhatIfSituationCluster",
    "WhatIfSituationContext",
    "WhatIfSituationGraph",
    "WhatIfSituationLink",
    "WhatIfSituationThread",
    "WhatIfWorld",
    "build_public_context",
    "build_candidate_generation_prompt",
    "build_saved_ranked_result_payload",
    "default_forecast_backend",
    "build_branch_point_benchmark",
    "build_multitenant_world_model_benchmark",
    "empty_public_context",
    "evaluate_branch_point_benchmark_model",
    "export_workspace_history_snapshot",
    "score_historical_tail",
    "build_decision_scene",
    "build_saved_decision_scene",
    "get_research_pack",
    "judge_branch_point_benchmark",
    "list_branch_candidates",
    "list_branch_point_benchmark_models",
    "list_objective_packs",
    "list_research_packs",
    "list_supported_scenarios",
    "load_branch_point_benchmark_build_result",
    "load_branch_point_benchmark_eval_result",
    "load_branch_point_benchmark_judge_result",
    "load_branch_point_benchmark_study_result",
    "load_branch_point_benchmark_train_result",
    "load_experiment_result",
    "load_episode_manifest",
    "load_research_pack_run_result",
    "load_ranked_experiment_result",
    "load_world",
    "materialize_episode",
    "MultiTenantBenchmarkSource",
    "providers",
    "recommend_branch_thread",
    "replay_episode_baseline",
    "resolve_saved_whatif_bundle",
    "resolve_whatif_company_history_path",
    "resolve_whatif_mail_archive_path",
    "resolve_whatif_rosetta_dir",
    "resolve_whatif_source_path",
    "run_research_pack",
    "search_events",
    "select_specific_event",
    "train_branch_point_benchmark_model",
    "validate_candidate_diversity",
    "run_branch_point_benchmark_study",
    "run_branch_point_benchmark_prediction",
    "run_counterfactual_experiment",
    "run_ranked_counterfactual_experiment",
    "run_ejepa_counterfactual",
    "estimate_counterfactual_delta",
    "run_llm_counterfactual",
    "run_whatif",
]

_API_EXPORTS = {
    "build_public_context",
    "build_candidate_generation_prompt",
    "build_saved_ranked_result_payload",
    "score_historical_tail",
    "build_decision_scene",
    "build_saved_decision_scene",
    "empty_public_context",
    "export_workspace_history_snapshot",
    "build_multitenant_world_model_benchmark",
    "list_branch_candidates",
    "list_objective_packs",
    "list_supported_scenarios",
    "load_experiment_result",
    "load_episode_manifest",
    "load_ranked_experiment_result",
    "load_world",
    "materialize_episode",
    "MultiTenantBenchmarkSource",
    "recommend_branch_thread",
    "replay_episode_baseline",
    "resolve_saved_whatif_bundle",
    "resolve_whatif_company_history_path",
    "resolve_whatif_mail_archive_path",
    "resolve_whatif_rosetta_dir",
    "resolve_whatif_source_path",
    "search_events",
    "select_specific_event",
    "run_counterfactual_experiment",
    "run_ranked_counterfactual_experiment",
    "run_branch_point_benchmark_prediction",
    "estimate_counterfactual_delta",
    "run_llm_counterfactual",
    "run_whatif",
    "validate_candidate_diversity",
}
_EJEPA_EXPORTS = {"default_forecast_backend", "run_ejepa_counterfactual"}
_RESEARCH_EXPORTS = {
    "get_research_pack",
    "list_research_packs",
    "load_research_pack_run_result",
    "run_research_pack",
}
_BENCHMARK_EXPORTS = {
    "build_branch_point_benchmark",
    "evaluate_branch_point_benchmark_model",
    "judge_branch_point_benchmark",
    "list_branch_point_benchmark_models",
    "load_branch_point_benchmark_build_result",
    "load_branch_point_benchmark_eval_result",
    "load_branch_point_benchmark_judge_result",
    "load_branch_point_benchmark_study_result",
    "load_branch_point_benchmark_train_result",
    "run_branch_point_benchmark_study",
    "run_branch_point_benchmark_prediction",
    "train_branch_point_benchmark_model",
}


def __getattr__(name: str) -> Any:
    if name in _MODEL_EXPORTS:
        module = import_module("vei.whatif.models")
        return getattr(module, name)
    if name == "providers":
        return import_module("vei.llm.providers")
    if name in _API_EXPORTS:
        module = import_module("vei.whatif.api")
        return getattr(module, name)
    if name in _EJEPA_EXPORTS:
        module = import_module("vei.whatif.ejepa")
        return getattr(module, name)
    if name in _RESEARCH_EXPORTS:
        module = import_module("vei.whatif.research")
        return getattr(module, name)
    if name in _BENCHMARK_EXPORTS:
        module = import_module("vei.whatif.benchmark")
        return getattr(module, name)
    raise AttributeError(f"module 'vei.whatif' has no attribute {name!r}")
